/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermercado1.pkg0.View;

import javax.swing.JFormattedTextField;
import supermercado1.pkg0.Controller.Message;
import supermercado1.pkg0.Controller.getImageBack;
import supermercado1.pkg0.Model.DAO.taxaDAO;

/**
 *
 * @author gildo
 */
public class desconto extends javax.swing.JFrame {

    /**
     * Creates new form desconto
     */
    private float subtotal,desc,perce,taxa,total, Taxa;
    private JFormattedTextField aux,aux2,aux3,aux4;
    public desconto() {
        initComponents();
        subtotal=Float.valueOf(sub.getText());
        taxa=Float.valueOf(cptotaldesc.getText());
        total=subtotal+taxa;
        this.total=Float.valueOf(cptotal.getText());
        setIconImage(new getImageBack().getImage());
        if(Taxa==0) ptaxa.setVisible(false);
    }
    
    public desconto(JFormattedTextField CPsub,float CPtaxa,JFormattedTextField CPtotal
            ,boolean istaxa,JFormattedTextField CPdesc,JFormattedTextField CPTaxa) 
    {
        initComponents();
        sub.setText(CPsub.getText());
        cptotal.setText(CPtotal.getText());
        aux=CPtotal;
        aux2=CPsub;
        aux3=CPdesc;
        aux4=CPTaxa;
        Taxa=(float) new taxaDAO().getValorTaxa();
        if(Taxa==0) ptaxa.setVisible(false);
        if(!istaxa)
        {
            Lcomdesconto.setVisible(istaxa);
            cptotaldesc.setVisible(istaxa);
            subtotal=Float.valueOf(sub.getText());
            total=subtotal;
            cptotaldesc.setText("");
        }else
        {
            
            cptotaldesc.setText("");
            subtotal=Float.valueOf(sub.getText());
            taxa=CPtaxa;
            cptaxa.setText(CPtaxa+"");
            
        }
        setIconImage(new getImageBack().getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rSButton2 = new rojeru_san.RSButton();
        rSButton1 = new rojeru_san.RSButton();
        valor = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        percetagem = new javax.swing.JFormattedTextField();
        Lcomdesconto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sub = new javax.swing.JFormattedTextField();
        cptotaldesc = new javax.swing.JFormattedTextField();
        cptotal = new javax.swing.JFormattedTextField();
        ptaxa = new javax.swing.JPanel();
        Ltaxa = new javax.swing.JLabel();
        cptaxa = new javax.swing.JFormattedTextField();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("APLICAR DESCONTO");
        setBackground(new java.awt.Color(255, 255, 255));
        setExtendedState(-1);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Subtotal:");

        rSButton2.setBackground(new java.awt.Color(0, 153, 0));
        rSButton2.setForeground(new java.awt.Color(0, 0, 0));
        rSButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/save.png"))); // NOI18N
        rSButton2.setText("SALVAR");
        rSButton2.setToolTipText("Confirmar...");
        rSButton2.setColorHover(new java.awt.Color(51, 255, 0));
        rSButton2.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        rSButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        rSButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton2ActionPerformed(evt);
            }
        });

        rSButton1.setBackground(new java.awt.Color(153, 153, 153));
        rSButton1.setForeground(new java.awt.Color(0, 0, 0));
        rSButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cancel_48px.png"))); // NOI18N
        rSButton1.setText("CANCELAR");
        rSButton1.setColorHover(new java.awt.Color(255, 0, 0));
        rSButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton1ActionPerformed(evt);
            }
        });

        valor.setBackground(new java.awt.Color(255, 204, 102));
        valor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 204), 1, true));
        valor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        valor.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        valor.setToolTipText("");
        valor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valorKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Desconto:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Percentagem:");

        percetagem.setBackground(new java.awt.Color(255, 204, 102));
        percetagem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 204), 1, true));
        percetagem.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        percetagem.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        percetagem.setToolTipText("");
        percetagem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        percetagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                percetagemKeyReleased(evt);
            }
        });

        Lcomdesconto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lcomdesconto.setText("TotalDesc:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Total:");

        sub.setEditable(false);
        sub.setBackground(new java.awt.Color(255, 204, 153));
        sub.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 204), 1, true));
        sub.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        sub.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        sub.setText("500.00");
        sub.setToolTipText("");
        sub.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        sub.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        cptotaldesc.setEditable(false);
        cptotaldesc.setBackground(new java.awt.Color(255, 204, 153));
        cptotaldesc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 204), 1, true));
        cptotaldesc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        cptotaldesc.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        cptotaldesc.setText("50");
        cptotaldesc.setToolTipText("");
        cptotaldesc.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        cptotaldesc.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        cptotal.setEditable(false);
        cptotal.setBackground(new java.awt.Color(255, 204, 153));
        cptotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));
        cptotal.setText("550.00");
        cptotal.setToolTipText("total a pagar...");
        cptotal.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        ptaxa.setBackground(new java.awt.Color(255, 255, 255));

        Ltaxa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Ltaxa.setText("Taxa:");

        cptaxa.setEditable(false);
        cptaxa.setBackground(new java.awt.Color(255, 204, 153));
        cptaxa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 204), 1, true));
        cptaxa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        cptaxa.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        cptaxa.setText("50");
        cptaxa.setToolTipText("");
        cptaxa.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        cptaxa.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        javax.swing.GroupLayout ptaxaLayout = new javax.swing.GroupLayout(ptaxa);
        ptaxa.setLayout(ptaxaLayout);
        ptaxaLayout.setHorizontalGroup(
            ptaxaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ptaxaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Ltaxa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cptaxa)
                .addContainerGap())
        );
        ptaxaLayout.setVerticalGroup(
            ptaxaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cptaxa)
            .addComponent(Ltaxa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lcomdesconto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rSButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rSButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(percetagem, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sub)
                    .addComponent(cptotaldesc)
                    .addComponent(cptotal))
                .addContainerGap())
            .addComponent(ptaxa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(percetagem, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Lcomdesconto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cptotaldesc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ptaxa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cptotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void valorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorKeyReleased
        float comdesc=0,tax;
        total=subtotal+taxa;
        try {
            this.desc=Float.valueOf(valor.getText());
            if(desc>=subtotal)
            {
                new Message().messageError("O desconto aplicado é inválido!");
                valor.setText("");
                percetagem.setText("");
                cptotal.setText((subtotal+taxa)+"");
                cptaxa.setText(taxa+"");
                aux4.setText(taxa+"");
                aux.setText(""+total);
                cptotaldesc.setText("");
                aux3.setText("");
            }else{
                comdesc=subtotal-desc;  
                tax=comdesc*Taxa/100;
                cptaxa.setText(tax+"");
                cptotaldesc.setText(comdesc+"");
                total=comdesc+tax;
                perce=(desc*100)/subtotal;
                aux4.setText(tax+"");
                percetagem.setText(perce+"%");
                cptotal.setText(""+total);
                aux.setText(""+total);
                aux3.setText(""+desc);
            }
        } catch (Exception e) {
            cptotal.setText(""+(subtotal+taxa));
            aux.setText(""+total);
            cptotaldesc.setText("");
            cptaxa.setText(taxa+"");
            aux4.setText(taxa+"");
            percetagem.setText("");aux3.setText("");
        }
    }//GEN-LAST:event_valorKeyReleased

    private void percetagemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_percetagemKeyReleased
        float comdesc,tax;
        total=subtotal+taxa;
        try {
            this.perce=Float.valueOf(percetagem.getText());
            if(perce>100)
            {
                new Message().messageError("O desconto aplicado é inválido!");
                percetagem.setText("");
                valor.setText("");
                cptotal.setText(""+total);
                aux.setText(""+total);
                cptotaldesc.setText("");aux3.setText("");aux4.setText(taxa+"");
            }else{
                desc=subtotal*perce/100;
                comdesc=subtotal-desc;  
                tax=comdesc*Taxa/100;
                cptaxa.setText(tax+"");
                cptotaldesc.setText(comdesc+"");
                total=comdesc+tax;
                valor.setText(desc+"");
                cptotal.setText(""+total);
                aux.setText(""+total);
                cptotaldesc.setText((subtotal-desc)+"");aux3.setText(""+desc);
                aux4.setText(tax+"");
            }
        } catch (Exception e) {
            cptotal.setText(""+total);
            aux.setText(""+total);cptotaldesc.setText("");
            valor.setText("");aux3.setText("");
            aux4.setText(taxa+"");
        }
    }//GEN-LAST:event_percetagemKeyReleased

    private void rSButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_rSButton2ActionPerformed

    private void rSButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton1ActionPerformed

        dispose();
    }//GEN-LAST:event_rSButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(desconto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(desconto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(desconto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(desconto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new desconto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lcomdesconto;
    private javax.swing.JLabel Ltaxa;
    private javax.swing.JFormattedTextField cptaxa;
    private javax.swing.JFormattedTextField cptotal;
    private javax.swing.JFormattedTextField cptotaldesc;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JFormattedTextField percetagem;
    private javax.swing.JPanel ptaxa;
    private rojeru_san.RSButton rSButton1;
    private rojeru_san.RSButton rSButton2;
    private javax.swing.JFormattedTextField sub;
    private javax.swing.JFormattedTextField valor;
    // End of variables declaration//GEN-END:variables
}
