/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermercado1.pkg0.View;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JTable;
import supermercado1.pkg0.Controller.Message;
import supermercado1.pkg0.Controller.getImageBack;
import supermercado1.pkg0.Model.Bean.categBean;
import supermercado1.pkg0.Model.DAO.categDAO;

/**
 *
 * @author gildo
 */
public class novacategoria extends javax.swing.JFrame {

    /**
     * Creates new form novacategoria
     */
    private JComboBox listaccat;
    private String situacao="SALVAR";
    private final JTable table;
    private categBean cb=null;
    public novacategoria() {
        initComponents();
        setIconImage(new getImageBack().getImage());
        this.table=null;
    }
    
    public novacategoria(JTable table) {
        initComponents();
        setIconImage(new getImageBack().getImage());
        this.table=table;
        this.situacao="CONTROLE";
    }
    
    
    public novacategoria(JTable table,int id,String nome) 
    {
        initComponents();
        setIconImage(new getImageBack().getImage());
        this.table=table;
        cb=new categBean(nome, id);
        this.nome.setText(nome);
        this.situacao="ACTUALIZAR";
    }
    
    public novacategoria(JComboBox listacat) 
    {
        initComponents();
        this.situacao="ADD";
        setIconImage(new getImageBack().getImage());
        this.listaccat=listacat;
        this.table=null;
    }
    
    public void limpo()
    {
        nome.setText("");
    }
    public void addCat(String text)
    {
        DefaultComboBoxModel lista=(DefaultComboBoxModel) this.listaccat.getModel();
        lista.addElement(text);
    }

    public void novaCategoria()
    {
        if(nome.getText().trim().isEmpty())
        {
            new Message().messageError("Preencha o campo em branco!");
        }else
        {
            categBean cb=new categBean();
            cb.setNome(nome.getText());
            categDAO cd=new categDAO();
            if(cd.novaCategoria(cb))
            {
                new Message().messageSucesso("Cadastrado com sucesso!!");
            }else
            {
                new Message().messageError("Verifique se a categoria não está cadastrado!");
            }
        }
    }
    
    public void updateCategoria()
    {
        if(nome.getText().trim().isEmpty())
        {
            new Message().messageError("Preencha o campo em branco!");
        }else
        {
            categDAO cd=new categDAO();
            cb.setNome(nome.getText());
            if(cd.uptadeCategoria(cb))
            {
                new Message().messageSucesso("Categoria actualizado com sucesso!!");
                cd.getCategoria(table);
                dispose();
            }else
            {
                new Message().messageError("Erro ao actualizar os dados!");
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nome = new rojerusan.RSMetroTextPlaceHolder();
        rSButton1 = new rojeru_san.RSButton();
        btok = new rojeru_san.RSButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Categoria");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Categoria:");

        nome.setBackground(new java.awt.Color(255, 204, 102));
        nome.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        nome.setForeground(new java.awt.Color(0, 0, 0));
        nome.setToolTipText("categoria...");
        nome.setBotonColor(new java.awt.Color(255, 0, 0));
        nome.setPhColor(new java.awt.Color(0, 0, 0));
        nome.setPlaceholder("Escrever categoria...");
        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });

        rSButton1.setBackground(new java.awt.Color(153, 153, 153));
        rSButton1.setForeground(new java.awt.Color(0, 0, 0));
        rSButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cancel_48px.png"))); // NOI18N
        rSButton1.setText("CANCELAR");
        rSButton1.setColorHover(new java.awt.Color(255, 0, 0));
        rSButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton1ActionPerformed(evt);
            }
        });

        btok.setBackground(new java.awt.Color(0, 153, 0));
        btok.setForeground(new java.awt.Color(0, 0, 0));
        btok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/save.png"))); // NOI18N
        btok.setText("SALVAR");
        btok.setToolTipText("Confirmar...");
        btok.setColorHover(new java.awt.Color(51, 255, 0));
        btok.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btok.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btok, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(rSButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btok, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rSButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btokActionPerformed

        if(situacao.equals("ADD"))
        {
            novaCategoria();addCat(nome.getText());
            dispose();
        }else if(situacao.equals("SALVAR"))
        {
            novaCategoria();
        }else if(situacao.equals("CONTROLE")){
            novaCategoria();
            new categDAO().getCategoria(table);
        }else{
            updateCategoria();
        }
        limpo();
    }//GEN-LAST:event_btokActionPerformed

    private void rSButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton1ActionPerformed

        dispose();
    }//GEN-LAST:event_rSButton1ActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        
        if(situacao.equals("ADD"))
        {
            novaCategoria();addCat(nome.getText());
            dispose();
        }else if(situacao.equals("SALVAR"))
        {
            novaCategoria();
        }else if(situacao.equals("CONTROLE")){
            novaCategoria();
            new categDAO().getCategoria(table);
        }else{
            updateCategoria();
        }
        limpo();
    }//GEN-LAST:event_nomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(novacategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(novacategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(novacategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(novacategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new novacategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton btok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private rojerusan.RSMetroTextPlaceHolder nome;
    private rojeru_san.RSButton rSButton1;
    // End of variables declaration//GEN-END:variables
}
