/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermercado1.pkg0.View;

import java.util.ArrayList;
import java.util.HashMap;
import supermercado1.pkg0.Controller.Message;
import supermercado1.pkg0.Controller.getImageBack;
import supermercado1.pkg0.Model.Bean.itensvenda;
import supermercado1.pkg0.Model.Bean.novavendaBean;
import supermercado1.pkg0.Model.DAO.relatorio;
import supermercado1.pkg0.Model.DAO.vendaDAO;

/**
 *
 * @author gildo
 */

public class vendaFinalizar extends javax.swing.JFrame {

    private novavendaBean nvb;
    private ArrayList<itensvenda> lista;
    private double recebido=0,troco=0,total=0;
    int venda=0;
    public vendaFinalizar() {
        initComponents();
        
    }
    
    public vendaFinalizar(novavendaBean nvb,ArrayList<itensvenda> lista) {
        initComponents();
        setIconImage(new getImageBack().getImage());
        this.lista=lista;
        this.nvb=nvb;
        this.venda=this.nvb.getID();
        setValue();
    }
    
    public final void setValue()
    {
        cliente.setText(nvb.getNomecliente());
        cptotal.setText("$"+nvb.getTotal());
        this.total=nvb.getTotal();
        cprecebido.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cliente = new javax.swing.JLabel();
        cptotal = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        pagamento = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cprecebido = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cptroco = new javax.swing.JFormattedTextField();
        operacao = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        imprimir = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Finalizar a Venda");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/administrator_male3_48px.png"))); // NOI18N
        jLabel1.setText("Cliente:");

        cliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cliente.setText("Consumidor");

        cptotal.setEditable(false);
        cptotal.setBackground(new java.awt.Color(255, 204, 153));
        cptotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        cptotal.setToolTipText("total a pagar...");
        cptotal.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        cptotal.setRequestFocusEnabled(false);
        cptotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cptotalActionPerformed(evt);
            }
        });
        cptotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cptotalKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Meio Pagamento:");

        pagamento.setBackground(new java.awt.Color(255, 204, 102));
        pagamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro" }));
        pagamento.setToolTipText("selecione o tipo de pagamento...");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Total:");

        cprecebido.setBackground(new java.awt.Color(255, 204, 102));
        cprecebido.setForeground(new java.awt.Color(0, 51, 204));
        cprecebido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        cprecebido.setToolTipText("valor recebido...");
        cprecebido.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        cprecebido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cprecebidoActionPerformed(evt);
            }
        });
        cprecebido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cprecebidoKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Recebido:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Troco:");

        cptroco.setEditable(false);
        cptroco.setBackground(new java.awt.Color(255, 204, 153));
        cptroco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        cptroco.setToolTipText("valor a devolver...");
        cptroco.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        cptroco.setRequestFocusEnabled(false);
        cptroco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cptrocoActionPerformed(evt);
            }
        });
        cptroco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cptrocoKeyReleased(evt);
            }
        });

        operacao.setBackground(new java.awt.Color(255, 204, 102));
        operacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        operacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Venda", "Pedido" }));
        operacao.setToolTipText("selecione o tipo de operação...");
        operacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operacaoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Operação:");

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Finalizar");
        jButton1.setToolTipText("Finalizar a venda...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        imprimir.setBackground(new java.awt.Color(255, 255, 255));
        imprimir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        imprimir.setSelected(true);
        imprimir.setText("Imprimir documento");
        imprimir.setToolTipText("imprimir documento sempre que efectuar uma venda?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pagamento, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cprecebido, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cptroco, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(operacao, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cptotal))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(operacao, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cptotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cprecebido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cptroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(imprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cptotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cptotalActionPerformed

        
    }//GEN-LAST:event_cptotalActionPerformed

    private void cptotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cptotalKeyReleased
        
    }//GEN-LAST:event_cptotalKeyReleased

    private void cprecebidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cprecebidoActionPerformed
        // TODO add your handling code here:
        finalizar();
    }//GEN-LAST:event_cprecebidoActionPerformed

    public void finalizar()
    {
        nvb.setSituacao(operacao.getSelectedItem().toString());
        nvb.setTroco(troco);
        nvb.setPagamento(pagamento.getSelectedItem().toString());
        if(recebido==0 && pagamento.getSelectedIndex()==0 ||recebido<total)
        {
            cprecebido.requestFocus();
        }else
        if(new vendaDAO().vender(nvb))
        {
            if(new vendaDAO().itensvender(lista))
            {
                new Message().messageSucesso("Venda efectuado com sucesso!!!");
                imprimir();
                dispose();
                new novaVenda().setVisible(true);
            }
        }
    }
    
    public void imprimir()
    {
        if(imprimir.isSelected())
        {
            String fileName="src/report/novorecibo.jasper";
            HashMap para = new HashMap();
            para.put("table_id", this.venda);
            relatorio.imprimir(fileName, para);
        }
    }
    
    private void cprecebidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cprecebidoKeyReleased
        if(pagamento.getSelectedIndex()==0)
        {
            try 
            {
                recebido=Double.valueOf(cprecebido.getText());
                if(recebido>total)
                {
                    troco=recebido-total;
                    cprecebido.setText(""+recebido);
                    cptroco.setText(""+troco);
                }else if(recebido==total)
                {
                    troco=0.00;
                }
                
            } catch (Exception e) 
            {
                recebido=0.00;
                troco=0.00;
                cptroco.setText(""+troco);
            }
        }
    }//GEN-LAST:event_cprecebidoKeyReleased

    
    private void cptrocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cptrocoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cptrocoActionPerformed

    private void cptrocoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cptrocoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cptrocoKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        finalizar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void operacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operacaoActionPerformed
        nvb.setSituacao(operacao.getSelectedItem().toString());
        nvb.setTroco(troco);
        nvb.setPagamento("Dinheiro, Cheque, Cartão");
        if(operacao.getSelectedIndex()==1)
        {
            if(new vendaDAO().pedido(nvb))
            {
                if(new vendaDAO().itenspedido(lista))
                {
                    new Message().messageSucesso("Pedido efectuado com sucesso!!!");
                    dispose();
                    new novaVenda().setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_operacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vendaFinalizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vendaFinalizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vendaFinalizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vendaFinalizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vendaFinalizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cliente;
    private javax.swing.JFormattedTextField cprecebido;
    private javax.swing.JFormattedTextField cptotal;
    private javax.swing.JFormattedTextField cptroco;
    private javax.swing.JCheckBox imprimir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> operacao;
    private javax.swing.JComboBox<String> pagamento;
    // End of variables declaration//GEN-END:variables
}
